# Generated by Django 3.2.6 on 2021-08-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210820_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordaccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='discordaccount',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
