# Generated by Django 3.2.6 on 2021-08-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210820_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyport',
            name='ip_port',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
