# Generated by Django 3.2.5 on 2021-07-25 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('blacklisted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('blacklisted', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(to='mainapp.Member')),
            ],
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('delay', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('add_users', models.BooleanField(default=False)),
                ('message_stop', models.IntegerField()),
                ('discord_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.discordaccount')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.discordserver')),
            ],
        ),
    ]
