# Generated by Django 3.2.5 on 2021-07-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_discordserver_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordserver',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
