# Generated by Django 3.2.5 on 2021-07-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_discordserver_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordserver',
            name='natural_members_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
