# Generated by Django 3.2.5 on 2021-08-01 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0005_alter_discordserver_natural_members_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='discord_account',
        ),
        migrations.RemoveField(
            model_name='discordserver',
            name='natural_members_count',
        ),
        migrations.RemoveField(
            model_name='discordserver',
            name='users',
        ),
        migrations.RemoveField(
            model_name='member',
            name='blacklisted',
        ),
        migrations.AddField(
            model_name='directmessage',
            name='sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='discordserver',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='discordserver',
            name='members',
        ),
        migrations.AddField(
            model_name='discordserver',
            name='members',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MemberServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklisted', models.BooleanField(default=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('discord_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.discordserver')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.member')),
            ],
        ),
    ]
