# Generated by Django 3.2.5 on 2021-08-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210801_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordserver',
            name='blacklisted',
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='link',
            field=models.URLField(),
        ),
    ]
