# Generated by Django 3.2.5 on 2021-08-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_discordserver_last_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordserver',
            name='icon',
            field=models.URLField(blank=True),
        ),
    ]
