# Generated by Django 3.2.6 on 2021-08-03 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0011_discordserver_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BlacklistParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='discord_server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.discordserver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='MemberServer',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='blacklist_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.blacklistparent'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='blacklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.blacklistparent'),
        ),
    ]
