# Generated by Django 3.2.6 on 2021-08-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210803_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='delay',
            field=models.IntegerField(),
        ),
    ]
