# Generated by Django 3.2.6 on 2021-08-13 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_discordaccount_use_count'),
        ('mainapp', '0013_auto_20210813_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
            preserve_default=False,
        ),
    ]
