# Generated by Django 3.2.6 on 2021-08-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_directmessage_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='server_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
