# Generated by Django 3.2.6 on 2021-08-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_directmessage_server_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='blacklist_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='message_stop',
            field=models.IntegerField(default=0),
        ),
    ]
