# Generated by Django 3.2.6 on 2021-08-18 21:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_directmessage_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 8, 18, 21, 1, 17, 370225, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
