# Generated by Django 3.2.6 on 2021-08-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_blacklistparent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='roles',
            field=models.TextField(default='Member', max_length=700),
        ),
    ]
