# Generated by Django 3.2.5 on 2021-07-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0002_packages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packages',
            new_name='Package',
        ),
    ]
