# Generated by Django 3.2.5 on 2021-07-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0003_rename_packages_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(default='This package credits you the amount of messages bought to help you message more users'),
        ),
    ]
