# Generated by Django 3.2.5 on 2021-07-27 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('paygate', '0006_package_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200, unique=True)),
                ('dm_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Completed'), ('3', 'Cancelled')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
